spring:
  application:
    name: grimo
  shell:
    interactive:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,modulith

grimo:
  workspace: ${user.home}/grimo-workspace
