spring:
  application:
    name: grimo
  main:
    web-application-type: servlet
  shell:
    interactive:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,modulith

grimo:
  workspace: ${user.home}/grimo-workspace
